from pathlib import Path
import pandas as pd

from systematic_trading_infra.mock_trading.config import DATA_PATH


# ---------------------------------------------------------------------
# Internal helper
# ---------------------------------------------------------------------
from pathlib import Path

def _get_latest_run_dir(base_dir: Path) -> Path | None:
    if not base_dir.exists():
        return None

    run_dirs = [
        d for d in base_dir.iterdir()
        if d.is_dir() and d.name.startswith("run_")
    ]

    if not run_dirs:
        return None

    return max(run_dirs, key=lambda d: d.stat().st_mtime)

def _load_parquet(file_name: str) -> pd.DataFrame:
    base_dir = Path(DATA_PATH)
    run_dir = _get_latest_run_dir(base_dir)
    print("📂 Reading from:", run_dir)

    if run_dir is None:
        return pd.DataFrame()

    path = run_dir / file_name

    if not path.exists():
        return pd.DataFrame()

    try:
        df = pd.read_parquet(path)
    except Exception:
        return pd.DataFrame()

    if df.empty:
        return pd.DataFrame()

    if "timestamp" in df.columns:
        df["timestamp"] = pd.to_datetime(df["timestamp"])
        df = df.sort_values("timestamp")
    elif isinstance(df.index, pd.DatetimeIndex):
        df = df.sort_index()

    return df



# ---------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------

def load_prices() -> pd.DataFrame:
    """
    Historical prices (long format).
    Columns: [timestamp, asset, price]
    """
    return _load_parquet("prices.parquet")


def load_signals() -> pd.DataFrame:
    """
    Trading signals.
    Columns: [timestamp, asset, signal]
    """
    return _load_parquet("signals.parquet")


def load_orders() -> pd.DataFrame:
    """
    Orders generated by the strategy.
    Columns: [timestamp, asset, side, quantity]
    """
    return _load_parquet("orders.parquet")


def load_portfolio_value() -> pd.DataFrame:
    """
    Portfolio NAV history.
    Index or column: timestamp
    Columns: [cash, nav]
    """
    return _load_parquet("portfolio_value.parquet")


def load_weights() -> pd.DataFrame:
    """
    Portfolio weights / positions.
    Columns: [timestamp, asset, weight]
    """
    return _load_parquet("weights.parquet")
